//! Guest create options, bounds, popup policy, and info snapshots.

use serde::{Deserialize, Serialize};
use serde_json::{Value, json};

use crate::bridge::BridgeError;

/// How a guest handles `window.open` / `target=_blank`.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum GuestPopupPolicy {
    /// Cancel the popup and emit `guest.newWindow` for the app to handle.
    #[default]
    Deny,
    /// Allow Chromium to open a native popup window.
    Allow,
    /// Open the URL inside the same guest (navigate in place).
    NavigateSame,
    /// Open the URL in a new guest surface with the same partition.
    OpenGuest,
}

impl GuestPopupPolicy {
    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "deny" | "block" => Some(Self::Deny),
            "allow" => Some(Self::Allow),
            "navigateSame" | "navigate_same" | "same" => Some(Self::NavigateSame),
            "openGuest" | "open_guest" | "guest" => Some(Self::OpenGuest),
            _ => None,
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Deny => "deny",
            Self::Allow => "allow",
            Self::NavigateSame => "navigateSame",
            Self::OpenGuest => "openGuest",
        }
    }
}

/// Pixel bounds of a guest relative to the host window client area.
///
/// Values are in **CSS pixels / DIPs** (what `getBoundingClientRect()`
/// returns). The OSR host converts them to physical pixels using the window DPI.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GuestBounds {
    pub x: i32,
    pub y: i32,
    pub width: u32,
    pub height: u32,
}

impl GuestBounds {
    pub fn new(x: i32, y: i32, width: u32, height: u32) -> Self {
        Self {
            x,
            y,
            width: width.max(1),
            height: height.max(1),
        }
    }

    pub fn normalized(self) -> Self {
        Self {
            x: self.x,
            y: self.y,
            width: self.width.max(1),
            height: self.height.max(1),
        }
    }
}

/// Options for creating a guest surface.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GuestCreateOptions {
    /// Stable guest id. Generated by the host when omitted.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Initial URL. Mutually exclusive with `html` when both are empty.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Inline HTML document loaded as a data URI when `url` is absent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
    #[serde(default)]
    pub bounds: GuestBounds,
    /// Cookie / cache partition key. Guests with the same partition share
    /// storage. Defaults to a private partition per guest id.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub partition: Option<String>,
    /// When true, inject `window.sabine` with the host allow-list.
    /// Defaults to false — guest pages are untrusted.
    #[serde(default)]
    pub allow_bridge: bool,
    /// Keyboard accelerators consumed by the host while this guest has focus.
    /// Supported modifiers are `Primary`, `Control`, `Meta`, `Alt`, and
    /// `Shift`, followed by one key (for example `Primary+K`). Matching input
    /// is emitted to the primary page as `guest.shortcut` and is not delivered
    /// to the guest.
    #[serde(default)]
    pub intercepted_shortcuts: Vec<String>,
    /// Consume horizontal wheel/trackpad input over this guest and emit it to
    /// the primary page as `guest.wheel`.
    #[serde(default)]
    pub intercept_horizontal_wheel: bool,
    #[serde(default = "default_true")]
    pub visible: bool,
    #[serde(default)]
    pub popup_policy: GuestPopupPolicy,
    /// When true, the guest may start downloads (emitted as events).
    #[serde(default = "default_true")]
    pub allow_downloads: bool,
    /// Optional background color as `#RRGGBB` or `#AARRGGBB`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub background_color: Option<String>,
}

fn default_true() -> bool {
    true
}

impl Default for GuestCreateOptions {
    fn default() -> Self {
        Self {
            id: None,
            url: None,
            html: None,
            bounds: GuestBounds::new(0, 0, 1, 1),
            partition: None,
            allow_bridge: false,
            intercepted_shortcuts: Vec::new(),
            intercept_horizontal_wheel: false,
            visible: true,
            popup_policy: GuestPopupPolicy::Deny,
            allow_downloads: true,
            background_color: None,
        }
    }
}

impl GuestCreateOptions {
    pub fn from_value(value: &Value) -> Result<Self, BridgeError> {
        let mut options: Self = if value.get("bounds").is_some() {
            serde_json::from_value(value.clone()).map_err(|error| {
                BridgeError::new(format!("invalid guest.create options: {error}"))
            })?
        } else {
            let mut without_bounds = value.clone();
            if let Some(object) = without_bounds.as_object_mut() {
                object.insert(
                    "bounds".to_string(),
                    json!({
                        "x": int_field(value, "x").unwrap_or(0),
                        "y": int_field(value, "y").unwrap_or(0),
                        "width": uint_field(value, "width").unwrap_or(1),
                        "height": uint_field(value, "height").unwrap_or(1),
                    }),
                );
            }
            serde_json::from_value(without_bounds).map_err(|error| {
                BridgeError::new(format!("invalid guest.create options: {error}"))
            })?
        };
        options.bounds = GuestBounds::new(
            int_field(value, "x").unwrap_or(options.bounds.x),
            int_field(value, "y").unwrap_or(options.bounds.y),
            uint_field(value, "width").unwrap_or(options.bounds.width),
            uint_field(value, "height").unwrap_or(options.bounds.height),
        )
        .normalized();
        if let Some(bounds) = value.get("bounds") {
            options.bounds = GuestBounds::new(
                int_field(bounds, "x").unwrap_or(options.bounds.x),
                int_field(bounds, "y").unwrap_or(options.bounds.y),
                uint_field(bounds, "width").unwrap_or(options.bounds.width),
                uint_field(bounds, "height").unwrap_or(options.bounds.height),
            )
            .normalized();
        }
        if options.url.as_deref().is_none_or(str::is_empty)
            && options.html.as_deref().is_none_or(str::is_empty)
        {
            return Err(BridgeError::new(
                "guest.create requires a non-empty `url` or `html`",
            ));
        }
        if let Some(id) = &options.id {
            let id = normalize_guest_id(id)?;
            options.id = Some(id);
        }
        if let Some(policy) = value
            .get("popupPolicy")
            .or_else(|| value.get("popup_policy"))
            .and_then(Value::as_str)
        {
            options.popup_policy = GuestPopupPolicy::parse(policy)
                .ok_or_else(|| BridgeError::new(format!("unknown guest popupPolicy: {policy}")))?;
        }
        Ok(options)
    }
}

/// Snapshot of a live guest returned by `list` / `get` / `create`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GuestInfo {
    pub id: String,
    pub url: String,
    pub title: String,
    pub bounds: GuestBounds,
    pub visible: bool,
    pub loading: bool,
    pub can_go_back: bool,
    pub can_go_forward: bool,
    pub partition: String,
    pub allow_bridge: bool,
    pub popup_policy: GuestPopupPolicy,
    pub zoom_factor: f64,
}

impl GuestInfo {
    pub fn to_json(&self) -> Value {
        json!({
            "id": self.id,
            "url": self.url,
            "title": self.title,
            "bounds": {
                "x": self.bounds.x,
                "y": self.bounds.y,
                "width": self.bounds.width,
                "height": self.bounds.height,
            },
            "x": self.bounds.x,
            "y": self.bounds.y,
            "width": self.bounds.width,
            "height": self.bounds.height,
            "visible": self.visible,
            "loading": self.loading,
            "canGoBack": self.can_go_back,
            "canGoForward": self.can_go_forward,
            "partition": self.partition,
            "allowBridge": self.allow_bridge,
            "popupPolicy": self.popup_policy.as_str(),
            "zoomFactor": self.zoom_factor,
        })
    }
}

pub fn normalize_guest_id(id: &str) -> Result<String, BridgeError> {
    let trimmed = id.trim();
    if trimmed.is_empty() {
        return Err(BridgeError::new("guest id must not be empty"));
    }
    if trimmed.len() > 128 {
        return Err(BridgeError::new("guest id must be at most 128 characters"));
    }
    if !trimmed
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_' || c == '.')
    {
        return Err(BridgeError::new(
            "guest id may only contain ASCII alphanumerics, '-', '_', and '.'",
        ));
    }
    Ok(trimmed.to_string())
}

pub(crate) fn int_field(value: &Value, key: &str) -> Option<i32> {
    value.get(key).and_then(|item| {
        item.as_i64()
            .map(|n| n as i32)
            .or_else(|| item.as_f64().map(|n| n as i32))
    })
}

pub(crate) fn uint_field(value: &Value, key: &str) -> Option<u32> {
    value.get(key).and_then(|item| {
        item.as_u64()
            .map(|n| n as u32)
            .or_else(|| item.as_f64().map(|n| n.max(0.0) as u32))
            .or_else(|| item.as_i64().map(|n| n.max(0) as u32))
    })
}

pub(crate) fn bool_field(value: &Value, key: &str) -> Option<bool> {
    value.get(key).and_then(Value::as_bool)
}
