use serde::Serialize;

/// How a guest handles `window.open` / `target=_blank`.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum GuestPopupPolicy {
    /// Cancel the popup and emit `guest.newWindow` for the app to handle.
    #[default]
    Deny,
    /// Allow Chromium to open a native popup window.
    Allow,
    /// Open the URL inside the same guest (navigate in place).
    NavigateSame,
    /// Open the URL in a new guest surface with the same partition.
    OpenGuest,
}

/// Pixel bounds of a guest relative to the host window client area.
///
/// Values are in **CSS pixels / DIPs** (what `getBoundingClientRect()`
/// returns). The OSR host converts them to physical pixels using the window DPI.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize)]
pub struct GuestBounds {
    pub x: i32,
    pub y: i32,
    pub width: u32,
    pub height: u32,
}

impl GuestBounds {
    pub fn new(x: i32, y: i32, width: u32, height: u32) -> Self {
        Self {
            x,
            y,
            width: width.max(1),
            height: height.max(1),
        }
    }
}

/// Options for creating a guest surface.
#[derive(Clone, Debug, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GuestCreateOptions {
    /// Stable guest id. Generated by the host when omitted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Initial URL. `html` is loaded instead when this is absent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Inline HTML document loaded as a data URI when `url` is absent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
    pub bounds: GuestBounds,
    /// Cookie / cache partition key. Guests with the same partition share
    /// storage. Defaults to a private partition per guest id.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub partition: Option<String>,
    /// When true, inject `window.sabine` with the host allow-list.
    /// Defaults to false — guest pages are untrusted.
    pub allow_bridge: bool,
    /// Keyboard accelerators consumed by the host while this guest has focus.
    /// Supported modifiers are `Primary`, `Control`, `Meta`, `Alt`, and
    /// `Shift`, followed by one key (for example `Primary+K`). Matching input
    /// is emitted to the primary page as `guest.shortcut` and is not delivered
    /// to the guest.
    pub intercepted_shortcuts: Vec<String>,
    /// Consume horizontal wheel/trackpad input over this guest and emit it to
    /// the primary page as `guest.wheel`.
    pub intercept_horizontal_wheel: bool,
    pub visible: bool,
    pub popup_policy: GuestPopupPolicy,
    /// When true, the guest may start downloads (emitted as events).
    pub allow_downloads: bool,
    /// Optional background color as `#RRGGBB` or `#AARRGGBB`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub background_color: Option<String>,
}

impl Default for GuestCreateOptions {
    fn default() -> Self {
        Self {
            id: None,
            url: None,
            html: None,
            bounds: GuestBounds::new(0, 0, 1, 1),
            partition: None,
            allow_bridge: false,
            intercepted_shortcuts: Vec::new(),
            intercept_horizontal_wheel: false,
            visible: true,
            popup_policy: GuestPopupPolicy::Deny,
            allow_downloads: true,
            background_color: None,
        }
    }
}
